In [ ]:
#1


In [ ]:
import numpy as np


In [ ]:
arr1=np.arange(1,11)

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#2

In [ ]:
arr2=np.zeros((2,3))

In [ ]:
arr2


array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#3

In [ ]:
arr3=np.arange(2,21,2)

In [ ]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#4

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr2=np.array([4,5,6])

In [ ]:
arr1+arr2

array([5, 7, 9])

In [ ]:
arr1-arr2

array([-3, -3, -3])

In [ ]:
arr1*arr2

array([ 4, 10, 18])

In [ ]:
arr1/arr2

array([0.25, 0.4 , 0.5 ])

In [ ]:
#5

In [ ]:
arr1=np.random.randint(1,101,100)

In [ ]:
arr1

array([ 35,  36,  32,  95,  83,  23,  79,  16,  43,  92,  90,  48,  93,
        33,  20,  66,  59,  53,  56, 100,  42,  96,  34,  54,  89,  49,
        11,  60,  35,  23,   1,  56,   5,  93,  33,  31,  33,  23,  10,
        87,  23,   6,  57,  12,  89,  18,  23,  77,  78,  23,  44,  81,
        81,  52,  17,   1,   7,   3,  72,  12,  56,  92,  38,  74,  19,
        60,  84,  90,  73,  62,  40,  83,  18,  75,  81,  87,  77,  14,
        45,   6,  86,  79,  44,   8,  85, 100,  19,  89,   6,  59,  35,
        66,  24,  53,   3,  58,  96,  80,  56,  26])

In [ ]:
#6

In [ ]:
arr1=np.random.randint(1,101,12)

In [ ]:
arr1

array([50, 93, 82, 83, 32, 83, 74, 17, 32, 44, 59, 90])

In [ ]:
arr1.reshape(3,4)

array([[50, 93, 82, 83],
       [32, 83, 74, 17],
       [32, 44, 59, 90]])

In [ ]:
#7



In [ ]:
arr=np.array([1,2,3,4,5])
np.square(arr)

array([ 1,  4,  9, 16, 25])

In [ ]:
#8

In [ ]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#9

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [ ]:
a.dot(b)

32

In [ ]:
#10

In [ ]:
arr1=np.random.randint(1,101,10)

In [ ]:
arr1


array([38, 91, 50,  3, 15, 48, 13, 31, 73, 66])

In [ ]:
arr1.argmax()

1

In [ ]:
arr1.argmin()

3

In [ ]:
#11

In [ ]:
a=np.zeros((4,4))
b=np.ones((4,4))
c=np.concatenate((a,b))
d=np.concatenate((a,b),axis=1)
print('vertical concatenate-\n',c)
print('horizontal concatenate-\n',d)


vertical concatenate-
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
horizontal concatenate-
 [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]


In [ ]:
#12

In [ ]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print('sum of each column is',np.sum(arr,axis=0))
print('sum of each row is',np.sum(arr,axis=1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
sum of each column is [28 32 36 40]
sum of each row is [10 26 42 58]


In [ ]:
#13

In [ ]:
a=np.array([[4,9],[5,8],[1,7]])
b=np.array([[3,9],[5,2],[6,7]])
c=np.intersect1d(a,b)
print("the commen elements between a andb are",c)

the commen elements between a andb are [5 7 9]


In [ ]:
#14

In [ ]:
x=np.array([1,2,3,-4,-5,-6])
x[x<0]=0
x

array([1, 2, 3, 0, 0, 0])

In [ ]:
#15

In [ ]:
arr1=np.random.randint(1,101,100)
arr1.sort()
arr1

array([ 1,  2,  2,  3,  5,  6,  7,  8,  8, 10, 11, 11, 15, 16, 17, 17, 18,
       18, 21, 23, 23, 23, 24, 24, 26, 26, 27, 27, 28, 28, 29, 29, 32, 32,
       32, 33, 34, 34, 35, 36, 38, 39, 39, 39, 41, 44, 44, 44, 46, 48, 50,
       50, 50, 51, 54, 54, 55, 55, 56, 60, 61, 63, 64, 64, 65, 67, 67, 68,
       69, 70, 71, 71, 73, 73, 74, 74, 74, 74, 74, 75, 75, 78, 79, 80, 81,
       81, 82, 82, 84, 87, 88, 88, 89, 90, 93, 93, 95, 97, 97, 98])

In [ ]:
#16


In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([6,8,10,12,14])
c=np.absolute(a-b)
print("the element-wise absolute difference between the two arrays is",c)

the element-wise absolute difference between the two arrays is [5 6 7 8 9]


In [ ]:
#17

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print("irst row is \n",firstrow)
print("last column is\n",lastcol)



irst row is 
 [1 2 3]
last column is
 [[3]
 [6]
 [9]]


In [ ]:
#18

In [ ]:
a=np.array([1,2,3,4,5])
x=a[0:len(a)+1]
print(x)

[1 2 3 4 5]


In [ ]:
#19

In [ ]:
arr=np.array([[10,1,14,16,18,20],[22,24,26,28,30,32],[34,36,38,40,42,44],[46,48,50,52,54,56],[58,60,62,64,66,68],[70,72,74,76,78,80]])
x=arr[2:4,[2,3]]
print('original array is\n',arr)
print('central 2x2 elements include\n',x)

original array is
 [[10  1 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]
central 2x2 elements include
 [[38 40]
 [50 52]]


In [ ]:
#20

In [ ]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])